name: Semgrep SAST Scan

on:
  pull_request:
    branches:
      - main  # adjust if your default branch is different

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ensures complete history for PR diff

      - name: Run Semgrep and post PR comments
        uses: returntocorp/semgrep-action@v1
        with:
          publishToken: ${{ secrets.SEMGREP }}
          baselineRef: origin/main
          generateSarif: true
        

